#Config file of iZone plugin

#if normal player can create private areas
non-op-create: true

#Protect from exploxion
protect-from-explosion: true

#Explosion Radius Protection
explosion-radius: 8

#Maximum x-length of the area
maximum-x: 30

#Maximum y-height of the area
maximum-y: 30

#Maximum z-width of the area
maximum-z: 30

#Data Provider [ yml, mysql, sql, none ]
data-provider: yml

#For MySQL:
#dataProviderSettings:
# host: "127.0.0.1"
# port: 3306
# user: "user"
# password: "password"
# database: "databaseName"
dataProviderSettings: []
